export const TODO_FORM = {
  CHANGE_CONTEXT: 'CHANGE_CONTEXT',
  CHANGE_DATE: 'CHANGE_DATE',
  CHANGE_TIME: 'CHANGE_TIME',
};

export const TODO_MODAL = {
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
};

export const TODO_SETTINGS = {
  SET_COLOR: 'SET_COLOR',
};
